### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by LegoStormtroopr** [jazzband/django-dbtemplates#80]
Is this still being maintained by JazzBand?

I'm interested in using this project, but it doesn't seem that many recent PRs have been merged and it hasn't had a PyPI release since last year.

**Comment by jezdez** [comment]
@LegoStormtroopr Thanks for the inquiry, the project is still maintained by the Jazzband members. I encourage you to read up about how [Jazzband](https://jazzband.co) works in case you'd like to help reviewing the pull requests and make sure new releases can happen.

**Comment by LegoStormtroopr** [comment]
I've read up on Jazzband before, it just seems there are sufficient changes since v1.3 to push a release to PyPI. Is that part of what Jazzband does?

**Comment by matthiask** [comment]
The Jazzband does what its members do.

Since you're interested in dbtemplates why not join and help out? 

Thanks!

**Comment by LegoStormtroopr** [comment]
No, thanks though. I already have responsibility for enough libraries on PyPI.

I just need to know if the Jazzband does push libraries to PyPI - if not I'm happy to maintain my own fork, I would just like to know either way.

**Comment by jezdez** [comment]
@LegoStormtroopr Of course Jazzband members can push a release on their own to PyPI. Just make sure the changelog, docs, version numbers etc are up-to-date and then push a git tag matching the Python package version to the repo. In other words, some work is always needed to do a release. The actual upload will happen automatically via Travis-CI.

A legitimate alternative is to at least open a ticket ~"Release ready, please push to PyPI" so other Jazzband members can pick it up and do the release. We're all volunteers here, so that's a sensible step to do but doesn't mean you can be sure when it happens.
