### ISSUE TITLE
conflict with django.contrib.flatpages 

### ISSUE THREAD

**Issue by x007007007** [jazzband/django-dbtemplates#84]
django flatpage can without site_id and auto switch site by request, but django-dbtemplates must set django site id. Unfortunately  when I setting site id , flatpage only know what I set. flatpage can not switch site from request. I want to know why we need site

**Comment by michaelkuty** [comment]
I think that every site could have own templates

**Comment by x007007007** [comment]
I'm agree with you, every site could have own templates. but when view or some thing render template , template don't know how to switch current site. because template can not get http response. But we set site_id , everything look like OK, but why we need the contrib.sites ? I think contrib.sites is work for switch site from http response automatic. did I have mistake

**Comment by x007007007** [comment]
I don't know,Is django have some way to access http request like flask, if have we can switch correctly site from request.

**Comment by jezdez** [comment]
No, Django's doesn't provide a thread local to the current request. Dbtemplates was written at a time at which `django.contrib.sites.shortcuts.get_current_site` wasn't used by flatpages. When you look at the code for this function you'll see that it'll only fall back to use a request based site object if django.contrib.sites isn't installed in INSTALLED_APPS. Since dbtemplates requires that application I'm afraid that this is basically a feature of the flatpages app that you can't use. Closing as wontfix.

**Comment by x007007007** [comment]
OK, I just think site_id is not a good idea, Let me see what I can do, Think you for patience, have a good day
